apiVersion: kernloom.io/registry/v1alpha1
kind: Registry
metadata:
  name: kernloom-notification-bindings
  version: "0.2.0"
spec:
  channels:
    - id: log
      refPrefixes: [log., stdout, stderr]
    - id: email
      refPrefixes: [channel., mailinglist., email.]
    - id: file
      refPrefixes: [file., file://, ./, ../, /]
    - id: jsonl
      refPrefixes: [jsonl., file., file://, ./, ../, /]
  caseSystems:
    - id: incident_backend
    - id: case_backend
    - id: servicenow
    - id: jira
